### ISSUE TITLE
Implement GitHub Security

### ISSUE THREAD

**Issue by tcarmet** [scality/runner-manager#192]
# Implementing GitHub Security

## Static analysis with codeql

Implement static analysis inside the development workflow.

We should analyze at the very least our python code, but include everything else that may be useful.

Static analysis should run at PR time, on push to `main` (when merging), and on a weekly schedule.

## Dependabot

Configure dependabot to create PR on the project, it will create prs for at the very least our python code, but everything else that dependabot may support should be added as well.

Dependabot can be configured to run on a daily base.

Ensure that our CI is supporting the builds run by dependabot as you may need to review the `permissions` of the workflow to ensure that they can run successfully.

## Trivy

Make use of [trivy](https://github.com/aquasecurity/trivy-action), a tool developed by aqua and configure it to analyse our container image and upload the analysis result into GitHub security.

The workflow should run on every PR, on push to `main` (when merging), and on a weekly schedule.

```[tasklist]
### Tasks
- [x] Implement codeql
- [x] Implement dependabot
- [x] Implement trivy
```

**Comment by gaspardmoindrot** [comment]
https://colinsalmcorner.com/custom-codeql/

**Comment by gaspardmoindrot** [comment]
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

**Comment by gaspardmoindrot** [comment]
https://github.com/aquasecurity/trivy-action
https://aquasecurity.github.io/trivy/v0.18.3/

**Comment by gaspardmoindrot** [comment]
```
branches:
      - "dev*"
```

To run Dependabot on other branches

**Comment by gaspardmoindrot** [comment]
* Dependabot is checking dependencies for `docker`, `gitHub-actions` and `pip`. If needed, we can run Dependabot on other branches with :
```
branches:
      - "dev*"
```
Dependabot alerts are going to the Security tab in the part Dependabot.

* We added Trivy to the `build.yaml` file because we need the image `ghcr.io/${{ github.repository }}:${{ github.sha }}`. With the flag `exit-code: '1'` if there is an error, the build with turn red on the PR. You can see alerts on the part Code Scanning in the tab Security. It's possible to add a `severity` flag if we only want certain type of error `severity: HIGH,CRITICAL`.

* CodeQL is also added to the workflow by scanning `python`. You can see alerts on the part Code Scanning in the tab Security.

All of those Github Security are running every Monday Morning 8am UTC, on push and on PR
